# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create! email: 'demo@example.com', password: 'password'

def create_barrel(barrel_params)
  barrel_params[:image] = {
    io: File.open("app/assets/images/#{barrel_params[:image]}"),
    filename: barrel_params[:image]
  }

  begin
    Barrel.create! barrel_params
  rescue ActiveRecord::StatementInvalid => e
    warn "Failed to insert barrel '#{barrel_params[:name]}': #{e.message}. Retrying."
    sleep 0.25
    retry
  end
end

create_barrel(
  name: 'Wine Barrel',
  image: 'wine-barrel.jpg',
  description: <<~HTML,
    <p>Inspected for quality and backed by our barrel guarantee, these oak wine barrels are ready to infuse your wine with rich, complex flavor.</p>
    <h2>Features</h2>
    <ul>
      <li>24 month air-dried, 20mm thick split oak staves</li>
      <li>Premium, blended Central France forest origins</li>
      <li>Medium Long toast for lighter, longer barrel impact</li>
    </ul>
  HTML
  volume: 60,
  price: 949.99
)

create_barrel(
  name: 'Crash Barrel',
  image: 'sand-barrel.jpg',
  description: <<~HTML,
    <p>Standard issue sand-filled highway crash barrel.</p>
  HTML
  volume: 200,
  price: 299.99
)

create_barrel(
  name: 'Oil Barrel', 
  image: 'oil-barrel.jpg', 
  description: '', 
  volume: 55, 
  price: 123.99
)

create_barrel(
  name: 'Rain Barrel',
  image: 'rain-barrel.webp',
  description: <<~HTML,
    <p>The Rain Wizard 50 is a rustic, faux oak rain barrel with a distressed wood-grain texture that is highly detailed. It holds 50 gallons and has a fine mesh screen to keep out debris along with front-facing overflow. This barrel features connection points for linking to other rain barrels and a flat-back that can sit right up against exterior walls. A standard 3/4” brass spigot is included. Incredibly strong, this rain barrel can take heavy impacts and holds up against the weather thanks to its sturdy, BPA-free plastic construction.</p>
    <ul>
      <li>Made of BPA-free resin</li>
      <li>Linkable to other barrels for increased capacity using separately sold linking kit</li>
      <li>Resistant to rot, mold, mildew, and rotting</li>
    </ul>
    <h3>Brand</h3>
    <p>Good Ideas</p>
    <h3>Manufacturer Part Number</h3>
    <p>RW50-OAK</p>
    <h3>Manufacturer</h3>
    <p>Good Ideas</p>
    <h3>Assembled Product Weight</h3>
    <p>19 lb</p>
    <h3>Color</h3>
    <p>Oak</p>
    <h3>Material</h3>
    <p>Polyethylene</p>
    <h3>Model</h3>
    <p>RW50-OAK</p>
    <h3>Assembled Product Dimensions (L x W x H)</h3>
    <p>22.00 x 22.00 x 30.00 Inches</p>
  HTML
  volume: 50,
  price: 141.98
)

create_barrel(
  name: 'Gangplank Special',
  image: 'gangplank-special.png',
  description: '<p>Big damage. <strong>HUGE</strong>.</p>',
  volume: 950,
  price: 13.00
)

create_barrel(
  name: 'Scout Barrel',
  image: 'scout-barrel.jpg',
  description: '<p>Scout barrel. Scout IN barrel. BOO!</p>',
  volume: 69,
  price: 69.00
)

create_barrel(
  name: 'Double Barrel',
  image: 'double-barrel-shotgun.jpg',
  description: '<p>Shotgun</p>',
  volume: 2,
  price: 1300.00
)

create_barrel(
  name: 'Barrel Roll',
  image: 'barrel-roll.gif',
  description: '<p>That\'s actually an Aileron Roll.</p>',
  volume: 2,
  price: 37_500_000.0
)

create_barrel(
  name: 'Aquarium Barrel Decoration',
  image: 'aquarium-barrel-decoration.webp',
  description: '',
  volume: 0.001,
  price: 4.97
)

create_barrel(
  name: 'AI Generated Barrel',
  image: 'ai-wine-barrel.jpg',
  description: '<p>This barrel does not exist. Generated by <a href="https://www.craiyon.com/" target="_blank"/>Craiyon</a></p>',
  volume: 60,
  price: 0.25
)

create_barrel(
  name: '<script>alert("XSS")</script> Barrel',
  image: 'hax.jpg',
  description: <<~HTML,
    <script>alert("This script tag should be sanitized by Rails sanitizer.")</script>
    <p>While this paragraph should stay.</p>
  HTML
  volume: 0.1,
  price: 0.1
)
